### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by ghost** [nickypatson/TinderSwipeView#8]
Hi, I find out that if you have many cards there is an increasing level of memory during the swipe and after some point (it depends of the device ram capacity) the project crashes “Terminated due to memory error”

**Comment by nickypatson** [comment]
Good to hear that.  I will have a look and if any thing i can do. I will keep you posted .

**Comment by ghost** [comment]
I think this problem is caused by the fact that, to keep the undo button function active to go back to the previous elements, the array is never decreased. In this way all the cards remain in memory and when there are many of them (for example 180/200) the app crashes.
I solved keeping the undo button function active only for one previous element and every time a swipe is made (both to the left and to the right), the array is decreased by that particular element.

**Comment by nickypatson** [comment]
I think its the one way , or instead of keeping values in array create an object (keep xcenter and ycenter with blind values) on the moment undo button is pressed. I think this will sort out issue. May be in a couple of days i will try to push the changes 
 
Any way its good to hear the feedback much appreciated. 

Thanks
Nicky

**Comment by ghost** [comment]
Thank you for your project.
Andrea

**Comment by nickypatson** [comment]
Worth knowing. Closing issue now
